name:
env:
app_id: 
guild_id:  
token: 
logging:
    level: Debug # DebugLow < Debug < Info < Warning < Error < Critical < Audit
    audit_channel: 
    critical_channel: 
    error_channel: 
    warning_channel: 
    info_channel: 
    debug_channel: 
    debug_low_channel: 
    log_file:
google:
    enabled: 
    credentials: 
    token: 
    username:
    sheet_id: 
    sheet_name: 
web:
    hostname: 
    port: 
commands:
    angry_react:
        emoji_id:
    message:
        channel_id:
    birthday:
        role_id:
    good_food:
        channel_id: 
        role_id: 
    heartbeat:
        url: 
    feedback:
        channel_id: 
    kudos:
        channel_id: 
        approval_channel_id: 
    member:
        channel_id: 
        member_role_id: 
        external_role_id: 
        prospective_role_id: 
        staff_role_id: 
        alumni_role_id: 
    